### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by adammead** [avioconsulting/mule-health-check-api#27]
Validate/Certify the connector on Java 17. 

This connector depends on the current version of the AVIO Logger, which does not support Java 17, so at least that dependency will need to be updated.

**Comment by manikmagar** [comment]
Logger 3.0 with Java 17 support have removed an expression support for Logger's global configuration - See https://github.com/avioconsulting/mule-custom-logger/issues/71.

This health check API XML extension wraps a logger-config inside and uses expressions to initialize the logger config. This will now fail with Custom Logger 3.0, as the expressions are not supported by parameters.
 - 
https://github.com/avioconsulting/mule-health-check-api/blob/main/src/main/resources/org/mule/extensions/smart/connector/module-health-check.xml#L24C1-L38C87

```
	<property name="attributes"  type="string" order="1" displayName="Attributes" example="${attributes}" summary="Should always be the attributes predefined var" defaultValue="#[attributes]" use="OPTIONAL"/>
	<property name="environment" type="string" order="2" displayName="Environment" example="dev" summary="Environment Name" defaultValue="#[p('env')]" use="OPTIONAL"/>
	<property name="logCategory" type="string" order="3" displayName="Log category"   example="com.avioconsulting.mule.healthcheck" summary="Log category" use="REQUIRED"/>
	<property name="extSysFlowNames" type="string" order="4" displayName="External systems" example="flow-name-1,flow-name-2" summary="external systems flow names" use="OPTIONAL"/>
	<property name="healthCheckAppName" type="string" order="5" displayName="Logger app name" example="application-name" summary="health check app name" defaultValue="#[p('app.name')]" use="OPTIONAL"/>
	<property name="healthCheckAppVersion" type="string" order="6" displayName="Logger app version" example="1.0.0" summary="heatlh check app version" defaultValue="#[p('app.version')]" use="OPTIONAL"/>
	
	<!-- copy start -->
	
	<avio-logger:config
		name="Health_Check_Logger_Config"
		doc:name="Health Check Logger Config"
		doc:id="6e6c93ab-10c7-42bc-a5d2-1bcd3bbf60a9"
		applicationVersion="#[vars.healthCheckAppVersion]"
		applicationName="#[vars.healthCheckAppName]" defaultCategory="#[vars.logCategory]"/>
```

@adammead @adesjardin  We have two options here -
1. Add the expression support back in the logger config
2. Externalize the configuration of `Health_Check_Logger_Config` - Have the applications using Healthcheck API to create a global config named `Health_Check_Logger_Config` and configure it as needed with properties placeholders only.

**Comment by adesjardin** [comment]
I think putting the Global config in the consuming application makes sense.

Adam DesJardin

Chief Technology Officer

AVIO Consulting <https://www.avioconsulting.com/> • Accelerating Digital
Evolution

T: +1.972.608.4777 | M: +1.585.820.9046

8350 N Central Expressway, Suite 1900 | Dallas, TX 75206
<https://www.linkedin.com/company/avio-consulting/>
<https://www.facebook.com/avioconsulting/>
<https://twitter.com/avioconsulting>

**Comment by manikmagar** [comment]
Ok. Externalizing the logger config would also need consumer applications to add `mule-custom-logger` dependency to the application pom if they already don't have it. 

3. The third option could be to use predefined property names in the logger configuration inside the health check and have consumer applications define those properties. In this case, consumers do not have to manage the logger's dependency.

```
<avio-logger:config
		name="Health_Check_Logger_Config"
		doc:name="Health Check Logger Config"
		doc:id="6e6c93ab-10c7-42bc-a5d2-1bcd3bbf60a9"
		environment="${env}"
		applicationVersion="${app.version}"
		applicationName="${app.name}" defaultCategory="${healthcheck.log.category}"/>
```

**Comment by manikmagar** [comment]
We will go ahead with option#3 and have predefined property names.
